-- =============================================
-- Script Template
-- =============================================
USE [Walmart]
GO

/****** Object:  Table [dbo].[CIDADE]    Script Date: 05/28/2013 21:33:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CIDADE](
	[COD_CIDADE] [int] NOT NULL,
	[COD_ESTADO] [int] NOT NULL,
	[NOME] [varchar](50) NULL,
	[IC_CAPITAL] [bit] NULL,
 CONSTRAINT [PK_CIDADE] PRIMARY KEY CLUSTERED 
(
	[COD_CIDADE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CIDADE]  WITH CHECK ADD  CONSTRAINT [FK_CIDADE_ESTADO] FOREIGN KEY([COD_ESTADO])
REFERENCES [dbo].[ESTADO] ([COD_ESTADO])
GO

ALTER TABLE [dbo].[CIDADE] CHECK CONSTRAINT [FK_CIDADE_ESTADO]
GO

