USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CIDADE_SELECIONA')
DROP PROCEDURE CIDADE_SELECIONA
GO

CREATE PROCEDURE [dbo].[CIDADE_SELECIONA]
	@COD_CIDADE INT

AS
BEGIN

	SELECT COD_CIDADE, COD_ESTADO, NOME, IC_CAPITAL
	FROM CIDADE
	WHERE
		COD_CIDADE = @COD_CIDADE
END
GO

