USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CIDADE_INSERE')
DROP PROCEDURE CIDADE_INSERE
GO

CREATE PROCEDURE [dbo].[CIDADE_INSERE]
	@COD_CIDADE INT,
	@COD_ESTADO	INT,
	@NOME		VARCHAR(50),
	@IC_CAPITAL	BIT

AS
BEGIN

	INSERT INTO CIDADE
	(COD_CIDADE, COD_ESTADO, NOME, IC_CAPITAL)
	VALUES
	(@COD_CIDADE, @COD_ESTADO, @NOME, @IC_CAPITAL)

END
GO

