USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CIDADE_ATUALIZA')
DROP PROCEDURE CIDADE_ATUALIZA
GO

CREATE PROCEDURE [dbo].[CIDADE_ATUALIZA]
	@COD_CIDADE INT,
	@COD_ESTADO	INT,
	@NOME		VARCHAR(50),
	@IC_CAPITAL	BIT

AS
BEGIN

	UPDATE CIDADE
	SET
		COD_ESTADO = @COD_ESTADO,
		NOME = @NOME,
		IC_CAPITAL = @IC_CAPITAL
	WHERE
		COD_CIDADE = @COD_CIDADE
END
GO

