USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ESTADO_INSERE')
DROP PROCEDURE ESTADO_INSERE
GO

CREATE PROCEDURE [dbo].[ESTADO_INSERE]
	@COD_ESTADO	INT,
	@PAIS		VARCHAR(50),
	@NOME		VARCHAR(50),
	@SIGLA		CHAR(2),
	@REGIAO		VARCHAR(50)

AS
BEGIN

	INSERT INTO ESTADO
	(COD_ESTADO, PAIS, NOME, SIGLA, REGIAO)
	VALUES
	(@COD_ESTADO, @PAIS, @NOME, @SIGLA, @REGIAO)

END
GO

