USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ESTADO_ATUALIZA')
DROP PROCEDURE ESTADO_ATUALIZA
GO

CREATE PROCEDURE [dbo].[ESTADO_ATUALIZA]
	@COD_ESTADO	INT,
	@PAIS		VARCHAR(50),
	@NOME		VARCHAR(50),
	@SIGLA		CHAR(2),
	@REGIAO		VARCHAR(50)

AS
BEGIN

	UPDATE ESTADO
	SET
		PAIS = @PAIS, 
		NOME = @NOME, 
		SIGLA = @SIGLA, 
		REGIAO = @REGIAO
	WHERE
		COD_ESTADO = @COD_ESTADO
END
GO

