USE WALMART
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ESTADO_SELECIONA')
DROP PROCEDURE ESTADO_SELECIONA
GO

CREATE PROCEDURE [dbo].[ESTADO_SELECIONA]
	@COD_ESTADO	INT

AS
BEGIN

	SELECT COD_ESTADO, PAIS, NOME, SIGLA, REGIAO
	FROM ESTADO
	WHERE
		COD_ESTADO = @COD_ESTADO
END
GO

